---
title: "Downy Mildew (*Plasmodium viticola*) decision support tool"
author: "Paul Melloy"
date: "`r Sys.Date()`"
output: html_document
---

```{r install_libraries, message=FALSE, warning=FALSE, include=FALSE}
packages <- c("remotes",
              "data.table",
              "ggplot2")

lapply(packages,function(p){
   if(isFALSE(p %in% installed.packages()[,"Package"])){
      install.packages(p,dependencies = TRUE)
   }
})

if(isFALSE("epiphytoolR" %in% installed.packages()[, "Package"])) {
   remotes::install_github("https://github.com/PaulMelloy/epiphytoolR",
                           dependencies = TRUE,
                           ref = "fill_weather",upgrade = "always")
   }

if(isFALSE("viticolR" %in% installed.packages()[, "Package"])) {
   remotes::install_github("https://github.com/PaulMelloy/viticolaR",
                           dependencies = TRUE,
                           ref = "dev",upgrade = "always")
}

library(shiny)
library(data.table)
library(viticolaR)
library(shinythemes)
library(ggplot2)
source("R/ccs_styles.R")
source("R/est_dm_risk.R")

# Load the last model run
switch(Sys.info()["nodename"],
       agroecology = load("/homevol/shared/DM_dst_data.rda"),
       pepper = load("/home/shared/DM_dst_data.rda"))


# assign default model as North Tamborine
DMod <- DMod_list[["23-24_NTamborine"]]
```

This content is generated from local "Bureau of Meteorology" weather data and the
R package `viticolR`. 
A mechanistic compartment model to assist in fungicide decision support for 
downy mildew (*Plasmodia viticola*) primary infections in grapevines.

### Disclaimer:  
This app is to be used as a guide in making more informed fungicide management 
decisions. 
Individual circumstances and conditions may vary, and local conditions should be 
also considered when deciding on the appropriate fungicide application.  

Always apply fungicide according to the label recommendations.  

Model estimates primary inoculum dispersal only:  
This model uses weather inputs to estimate the steps in primary inoculum 
dispersal and therefore is influenced by the AWS accuracy. 
The closer the weather station to the vineyard, the more accurate the 
estimations. 
By default missing rainfall observations are filled with '0'.  

This model does not account for secondary infections. 
If downy mildew is already present on the leaves, an alternate fungicide approach 
should be considered as this decision support tool would be misleading once 
downy mildew is established in the vineyard disease can develop rapidly. 
Use of this model should be used to prevent primary leaf infections.  

***  

This model is translated and adapted from the published paper 
'A mechanistic model simulating primary infections of downy mildew in grapevine' 
authored by Vittorio Rossi, Tito Caffi, Simona Giosue and Riccardo Bugiani. 
This paper was first published in *Ecological Modelling* in **2008**. 
10.1016/j.ecolmodel.2007.10.046

***  
